### ISSUE TITLE
bug: `logout` function throws `ReferenceError: localStorage is not defined`

### ISSUE THREAD

**Issue by ttnsy** [alfonsusac/devscale-eventmaker#73]
## How to reproduce:
1. Go to `/login` page, and try to log in
2. After successfully logged in, go to `/`
3. There's an error message thrown from console:

```
⨯ src/lib/session.js (13:2) @ localStorage
 ⨯ ReferenceError: localStorage is not defined
    at logout (./src/lib/session.js:17:5)
    at handleLogout (./src/components/HeaderButtons.jsx:15:57)
    at HeaderButtons (./src/components/HeaderButtons.jsx:75:34)
  11 |
  12 | export function logout() {
> 13 |   localStorage.removeItem("user");
     |  ^
  14 |   Cookies.remove("token");
  15 | }
  16 |
```

**Comment by ttnsy** [comment]
Related to #70
